cloud:
  aws:
    credentials:
      access-key: xxxx
      secret-key: xxxx
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: formimagestorage

server:
  servlet:
    context-path: /Projetofinal
  port: 8090
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      format-sql: true
  datasource:
    username: xxxx
    password: xxxx
    url: xxxx
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 3
