export const errorMessage = {
    "AUTHENTICATION_ERROR" : "Não foi possível Autenticar",
    "UNAUTHORIZED_ERROR" : "Você não está Autorizado",
    "USER_ERROR" : "Não foi possível carregar as informações do Usuário",
    "SEARCH_ERROR" : "Não foi possível realizar sua Busca",
    "EMPTY_SEARCH" : "Não há resultados para sua Busca",
    "POST_LOAD_ERROR" : "Não foi possível carregar os Posts",
    "RANKING_LOAD_ERROR" : "Não foi possível carregar o Ranking",
    "TAG_LOAD_ERROR" : "Não foi possível carregar as Tags",
    "REPLY_LOAD_ERROR" : "Não foi possível carregar as Respostas",
    "VOTE_LOAD_ERROR" : "Não foi possível carregar as Interações.",
    "VOTE_ERROR" : "Não foi possível realizar a Interação.",
    "NEW_TAG_ERROR" : "Não foi possível criar esta Tag",
    "IMAGE_ERROR" : "Não é possível fazer Upload deste Arquivo",
    "IMAGE_TYPE_INFO" : "Somente arquivos JPEG, JPG e PNG podem ser Enviados",
    "POST_ERROR" : "Não é possível publicar esta Pergunta",
    "REPLY_ERROR" : "Não foi possível publicar esta Resposta",
    "TITLE_INFO" : "O Título deve possuir de 10 a 100 Caracteres",
    "TAG_INFO" : "Você deve selecionar de 1 a 5 Tags",
    "CONTENT_INFO" : "O Conteúdo deve possuir de 10 a 1000 Caracteres",
    "DELEGATE_ERROR" : "Não foi possível Delegar o Usuário a Monitor",
    "REVOKE_ERROR" : "Não foi possível Revogar o cargo de Monitor do Usuário",
    "NOTIFICATION_LOAD_ERROR" : "Não foi possível carregar as Notificações",
    "NOTIFICATION_CLEAR_ERROR" : "Não foi possível Limpar as Notificações",
    "NOTIFICATION_ERROR" : "Não foi possível acessar a Notificação",
    "DELETE_IMAGE_ERROR" : "Não foi possível excluir esta Imagem",
    "VERIFY_ERROR" : "Não foi possível alterar a Verificação da Resposta"
}
